title: "I am the Champion"
author: Gavin Young 
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am here to grow and learn. No matter what I have to go through. I will win, because I am a winner and a champion!"
  # social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
